# Generated by Django 3.0.7 on 2020-07-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('nid', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=160)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
