# Generated by Django 3.0.7 on 2020-07-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20200714_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Chambers',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChamberTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Chamber')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Treatment')),
            ],
        ),
        migrations.CreateModel(
            name='ChamberPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Chamber')),
            ],
        ),
        migrations.CreateModel(
            name='ChamberDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Chamber')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
        ),
    ]
