# Generated by Django 3.0.7 on 2020-07-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20200719_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chambertreatment',
            options={'verbose_name_plural': 'Chamber Treatments'},
        ),
    ]
